export type SeedRecord = Record<string, unknown>;
export type SeedCollections = Record<string, SeedRecord[]>;

function nowIso() {
  return new Date().toISOString();
}

export function createSeedCollections(): SeedCollections {
  const created = nowIso();

  return {
    cliniclocations: [
      {
        _id: 'clinic-noida',
        _createdDate: created,
        _updatedDate: created,
        locationName: 'Noida',
        address: '102, Jaipuria Plaza, Sec-26, Noida',
        contactNumber: '0120-4295211',
        operatingHours: 'Mon-Sat 10:00 AM - 7:00 PM',
        email: 'noida@drupadhyayahomeopathy.in',
      },
      {
        _id: 'clinic-delhi',
        _createdDate: created,
        _updatedDate: created,
        locationName: 'Delhi',
        address: 'G-16, Vardhman Sun-Rise Plaza, Vasundhara Enclave, Delhi-96',
        contactNumber: '011-47520627',
        operatingHours: 'Mon-Sat 10:00 AM - 7:00 PM',
        email: 'delhi@drupadhyayahomeopathy.in',
      },
    ],
    clinicsettings: [
      {
        _id: 'settings-noida',
        _createdDate: created,
        _updatedDate: created,
        clinicLocation: 'Noida',
        consultationFee: 1400,
        medicineFee: 400,
        defaultFollowUpDays: 28,
        backupLocation: 'E:\\HCMS Backup_RC',
        billingNotes: 'Default charges apply unless overridden during consultation.',
      },
      {
        _id: 'settings-delhi',
        _createdDate: created,
        _updatedDate: created,
        clinicLocation: 'Delhi',
        consultationFee: 1400,
        medicineFee: 400,
        defaultFollowUpDays: 28,
        backupLocation: 'E:\\HCMS Backup_RC',
        billingNotes: 'Default charges apply unless overridden during consultation.',
      },
    ],
    noteslibrary: [
      {
        _id: 'note-migraine',
        _createdDate: created,
        _updatedDate: created,
        clinicLocation: 'Noida',
        title: 'Migraine Protocol',
        category: 'Migraine',
        keywords: 'migraine headache stress',
        content: 'Review triggers, sleep routine, and medicine response before next follow-up. Continue remedy for 28 days unless acute symptoms worsen.',
        isArchived: false,
      },
      {
        _id: 'note-throat',
        _createdDate: created,
        _updatedDate: created,
        clinicLocation: 'Delhi',
        title: 'Acute Throat Irritation',
        category: 'ENT',
        keywords: 'throat fever acute',
        content: 'Track fever, throat irritation, and aggravation pattern. Use SOS remedy guidance in acute phase.',
        isArchived: false,
      },
    ],
    medicalcertificates: [
      {
        _id: 'cert-1',
        _createdDate: created,
        _updatedDate: created,
        clinicLocation: 'Noida',
        certificateNumber: 'MC-NOI-0001',
        patientId: 'PTNOI001',
        patientName: 'Rohan Mehta',
        doctorName: 'Dr. R.C. Upadhyaya',
        issueDate: '2026-02-20',
        diagnosisSummary: 'Migraine with recurrent stress-related episodes',
        restDays: 3,
        notes: 'Patient advised rest and reduced screen exposure for 3 days.',
        isArchived: false,
      },
    ],
    doctors: [
      {
        _id: 'doc-rc',
        _createdDate: created,
        _updatedDate: created,
        doctorName: 'Dr. R.C. Upadhyaya',
        specialization: 'Classical Homeopathy',
        qualifications: 'D.H.M.S. (JAIPUR)',
        yearsOfExperience: 25,
        clinicLocation: 'Noida',
      },
      {
        _id: 'doc-priya',
        _createdDate: created,
        _updatedDate: created,
        doctorName: 'Dr. Priya Upadhyaya',
        specialization: 'Homeopathic Medicine',
        qualifications: 'B.H.M.S., M.D. (Hom.)',
        yearsOfExperience: 15,
        clinicLocation: 'Delhi',
      },
    ],
    treatments: [
      { _id: 'tr-1', _createdDate: created, _updatedDate: created, treatmentName: 'Migraine' },
      { _id: 'tr-2', _createdDate: created, _updatedDate: created, treatmentName: 'Respiratory Diseases' },
      { _id: 'tr-3', _createdDate: created, _updatedDate: created, treatmentName: 'Skin Problems' },
    ],
    suppliers: [
      {
        _id: 'sup-1',
        _createdDate: created,
        _updatedDate: created,
        supplierName: 'SBL Pharma Distributor',
        contactPerson: 'Amit Sharma',
        phoneNumber: '9876543210',
      },
      {
        _id: 'sup-2',
        _createdDate: created,
        _updatedDate: created,
        supplierName: 'Dr. Reckeweg Supply',
        contactPerson: 'Neha Verma',
        phoneNumber: '9876501234',
      },
    ],
    homeopathicmedicines: [
      {
        _id: 'med-arnica-30',
        _createdDate: created,
        _updatedDate: created,
        medicineName: 'Arnica Montana',
        potency: '30C',
        formType: 'Globules',
        manufacturer: 'SBL',
        packSize: '30g',
        reorderLevel: 20,
        targetCoverageDays: 45,
        isActive: true,
      },
      {
        _id: 'med-bell-200',
        _createdDate: created,
        _updatedDate: created,
        medicineName: 'Belladonna',
        potency: '200C',
        formType: 'Globules',
        manufacturer: 'Dr. Reckeweg',
        packSize: '30g',
        reorderLevel: 15,
        targetCoverageDays: 45,
        isActive: true,
      },
      {
        _id: 'med-rhustox-q',
        _createdDate: created,
        _updatedDate: created,
        medicineName: 'Rhus Tox',
        potency: 'Q',
        formType: 'Liquid',
        manufacturer: 'SBL',
        packSize: '30ml',
        reorderLevel: 10,
        targetCoverageDays: 30,
        isActive: true,
      },
    ],
    inventorybatches: [
      {
        _id: 'batch-1',
        _createdDate: created,
        _updatedDate: created,
        clinicLocation: 'Noida',
        medicineSKU: 'Arnica Montana',
        batchNumber: 'ARN-30C-01',
        expiryDate: '2027-08-31',
        quantityAvailable: 35,
        supplierName: 'SBL Pharma Distributor',
        unitCost: 18,
        purchaseInvoiceNumber: 'INV-NOI-1001',
        receivedDate: '2026-02-14',
        stockStatus: 'Active',
      },
      {
        _id: 'batch-2',
        _createdDate: created,
        _updatedDate: created,
        clinicLocation: 'Delhi',
        medicineSKU: 'Arnica Montana',
        batchNumber: 'ARN-30C-02',
        expiryDate: '2027-11-30',
        quantityAvailable: 12,
        supplierName: 'SBL Pharma Distributor',
        unitCost: 18,
        purchaseInvoiceNumber: 'INV-DEL-1003',
        receivedDate: '2026-02-18',
        stockStatus: 'Active',
      },
      {
        _id: 'batch-3',
        _createdDate: created,
        _updatedDate: created,
        clinicLocation: 'Delhi',
        medicineSKU: 'Belladonna',
        batchNumber: 'BEL-200-01',
        expiryDate: '2026-06-20',
        quantityAvailable: 8,
        supplierName: 'Dr. Reckeweg Supply',
        unitCost: 22,
        purchaseInvoiceNumber: 'INV-DEL-1004',
        receivedDate: '2026-02-20',
        stockStatus: 'Expiring',
      },
    ],
    patients: [
      {
        _id: 'pat-1',
        _createdDate: created,
        _updatedDate: created,
        patientId: 'PTNOI001',
        patientName: 'Rohan Mehta',
        phoneNumber: '9810012345',
        mobileNumber: '9810012345',
        gender: 'Male',
        ageYears: 34,
        maritalStatus: 'Married',
        city: 'Noida',
        state: 'Uttar Pradesh',
        country: 'India',
        profession: 'Business Owner',
        isArchived: false,
        clinicLocation: 'Noida',
      },
      {
        _id: 'pat-2',
        _createdDate: created,
        _updatedDate: created,
        patientId: 'PTDEL001',
        patientName: 'Ananya Gupta',
        phoneNumber: '9810098765',
        mobileNumber: '9810098765',
        gender: 'Female',
        ageYears: 29,
        maritalStatus: 'Single',
        city: 'Delhi',
        state: 'Delhi',
        country: 'India',
        profession: 'Teacher',
        isArchived: false,
        clinicLocation: 'Delhi',
      },
    ],
    prescriptions: [
      {
        _id: 'rx-1',
        _createdDate: created,
        _updatedDate: created,
        prescriptionId: 'RX001',
        patientName: 'Rohan Mehta',
        patientId: 'PTNOI001',
        doctorName: 'Dr. R.C. Upadhyaya',
        prescriptionDate: '2026-02-20',
        medicinesAndDosages: 'Arnica Montana 30C - 4 pills TDS',
        notes: 'Review after 7 days',
        symptomsSummary: 'Migraine with stress triggers',
        nature: 'Chilly',
        craving: 'Salt',
        treatmentSummary: 'Continue medicine for 28 days and monitor headache frequency.',
        medicineLineItems: JSON.stringify([
          { medicineName: 'Arnica Montana 30C', dosageManagement: '4 pills TDS' },
          { medicineName: 'Rhus Tox Q', dosageManagement: '10 drops in water OD' },
        ]),
        treatmentForDays: 28,
        consultationCount: 1,
        followUpIntervalValue: 28,
        followUpIntervalUnit: 'days',
        nextConsultationDate: '2026-03-20',
        consultationCharge: 1400,
        medicineCharge: 400,
        totalAmount: 1800,
        amountPaidCash: 1500,
        amountPaidOnline: 0,
        balanceAmount: 300,
        billRequired: true,
        prescriptionRequired: true,
        receiptNumber: 'RCT-NOI-0001',
        cancelledReceipt: false,
        paymentStatus: 'Partial',
        isArchived: false,
        clinicLocation: 'Noida',
      },
      {
        _id: 'rx-2',
        _createdDate: created,
        _updatedDate: created,
        prescriptionId: 'RX002',
        patientName: 'Ananya Gupta',
        patientId: 'PTDEL001',
        doctorName: 'Dr. Priya Upadhyaya',
        prescriptionDate: '2026-02-22',
        medicinesAndDosages: 'Belladonna 200C - SOS',
        notes: '',
        symptomsSummary: 'Acute throat irritation',
        nature: 'Hot',
        craving: 'Sweet',
        treatmentSummary: 'SOS dosing with follow-up after one month.',
        medicineLineItems: JSON.stringify([
          { medicineName: 'Belladonna 200C', dosageManagement: 'SOS' },
        ]),
        treatmentForDays: 28,
        consultationCount: 1,
        followUpIntervalValue: 1,
        followUpIntervalUnit: 'months',
        nextConsultationDate: '2026-03-22',
        consultationCharge: 1400,
        medicineCharge: 400,
        totalAmount: 1800,
        amountPaidCash: 0,
        amountPaidOnline: 1800,
        balanceAmount: 0,
        billRequired: true,
        prescriptionRequired: true,
        receiptNumber: 'RCT-DEL-0001',
        cancelledReceipt: false,
        paymentStatus: 'Paid',
        isArchived: false,
        clinicLocation: 'Delhi',
      },
    ],
    stocktransactionledger: [
      {
        _id: 'txn-1',
        _createdDate: created,
        _updatedDate: created,
        transactionType: 'Stock In',
        medicineSku: 'Arnica Montana',
        quantityChange: 20,
        transactionDateTime: '2026-02-18T10:00:00.000Z',
        referenceIdentifier: 'ARN-30C-02',
        auditReason: 'Purchase Entry',
        clinicLocation: 'Delhi',
        supplierName: 'SBL Pharma Distributor',
        unitCost: 18,
        resultingQuantity: 12,
      },
      {
        _id: 'txn-2',
        _createdDate: created,
        _updatedDate: created,
        transactionType: 'Stock Out',
        medicineSku: 'Belladonna',
        quantityChange: -2,
        transactionDateTime: '2026-02-22T15:30:00.000Z',
        referenceIdentifier: 'RX002',
        auditReason: 'Dispensed to Patient',
        clinicLocation: 'Delhi',
        resultingQuantity: 8,
      },
    ],
    homesplashimages: [],
  };
}

export function cloneSeedCollections(): SeedCollections {
  return JSON.parse(JSON.stringify(createSeedCollections())) as SeedCollections;
}
